# First the question that I always ask to myself is "What is it and Why we are using it?"

### What is Numpy?
- Numpy is a Python library used for working with arrays

### Why use Numpy when we also have list to working with arrays in Python?
- Yes, you are right. In Python we have list to working with array but they are very slow to process if you have a tremendous of data.
- Numpy provide array object that is 50x faster than list in Python and it provide a lot of function for working with arrays

### For more information: https://github.com/numpy/numpy


<hr>

In [1]:
# We need to import it to use
import numpy as np

In [2]:
# We can convert a traditional list in Python to Numpy array
list1 = [1, 'a' , 'bc']
arr1 = np.array(list1)
arr1

array(['1', 'a', 'bc'], dtype='<U11')

In [3]:
# 2-D array
matrix2d = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(matrix2d)

### Built-in methods

- **arange()**: return array with given interval
- **zeros()**: generate arrays of zeros
- **ones()**: generate arrays of ones
- **linspace()**: return numeric sequences in given interval
- **eye()**: create indentity matrix
- **shape()**: return shape of the array
- **reshape()**: reshape the array
- **random.rand()**: create an array of given with random number from a "uniform distribution" over [0,1)
- **random.randn()**: create an array of given with random number from a "standard normal" distribution
- **random.randint()**: return random integers from `low` (inclusive) to `high` (exclusive)
- **max()**: return max value of the array
- **argmax()**: return index of max value of the array
- **min()**: return min value of the array
- **argmin()**: return index of min value of the array

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.linspace(0,100,3)

array([  0.,  50., 100.])

In [9]:
np.linspace(0,100,50)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
arr1 = np.arange(25)
arr1.shape

(25,)

In [12]:
arr1.reshape((5,5)).shape

(5, 5)

In [13]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
arr1.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**random.rand**

In [15]:
np.random.rand(10)

array([0.27152586, 0.05009503, 0.93461179, 0.46737791, 0.35114332,
       0.73872093, 0.96188882, 0.31782038, 0.8866254 , 0.32864282])

In [16]:
np.random.rand(3,3)

array([[0.99127774, 0.31133393, 0.56553548],
       [0.22079148, 0.54840367, 0.8076339 ],
       [0.51728855, 0.43201919, 0.76719332]])

In [17]:
np.random.rand(3,3,3)

array([[[0.3099036 , 0.37184236, 0.50169032],
        [0.78233714, 0.11329928, 0.95175829],
        [0.42606063, 0.57904299, 0.62096578]],

       [[0.33715415, 0.20584457, 0.17643197],
        [0.71708464, 0.70529123, 0.0426447 ],
        [0.22630241, 0.56879855, 0.52251073]],

       [[0.94919564, 0.22147465, 0.61464422],
        [0.76260588, 0.41805472, 0.99564015],
        [0.15265754, 0.4683089 , 0.80210096]]])

**random.randn**

In [18]:
np.random.randn(10)

array([ 1.93604841, -0.63758291, -0.55452222, -0.23473331, -0.30024468,
       -0.66146052,  0.15243317, -1.19114734,  0.3178689 ,  0.45714184])

In [19]:
np.random.randn(3,3)

array([[ 0.11439862,  0.39614113, -0.04230782],
       [ 1.47892839,  1.01391379,  0.15201045],
       [-0.19731869, -1.21636619, -0.7647463 ]])

In [20]:
np.random.rand(3,3,3)

array([[[0.14802884, 0.69465755, 0.65407587],
        [0.83665981, 0.31785548, 0.65326764],
        [0.78234931, 0.46908775, 0.67265208]],

       [[0.58492808, 0.22348328, 0.19649045],
        [0.28289574, 0.8665464 , 0.79725191],
        [0.13496238, 0.58250783, 0.25301297]],

       [[0.87386542, 0.19747058, 0.73653303],
        [0.57499835, 0.0060141 , 0.29288247],
        [0.19288124, 0.55123706, 0.02558014]]])

**random.randint**

In [21]:
np.random.randint(0,10)

6

In [22]:
np.random.randint(0,100,10)

array([95, 71, 50, 54, 77, 79, 49,  3, 63, 92])

**max,min**

In [23]:
newarr = np.random.randint(0,100,10)
newarr

array([75, 90, 52,  1, 65, 11, 48, 57, 11, 66])

In [24]:
newarr.max()

90

In [25]:
newarr.argmax() # index start at 0

1

In [26]:
newarr.min()

1

In [27]:
newarr.argmin()

3

<hr>

### Interacting with array using square bracket

In [28]:
# Create sample array to use
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# get value at index
arr[4]

4

In [30]:
# get interval of value
arr[0:4]

array([0, 1, 2, 3])

In [31]:
# change value at index
arr[5] = 100
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10])

In [32]:
# change value with a range of index
arr[0:2] = 100
arr

array([100, 100,   2,   3,   4, 100,   6,   7,   8,   9,  10])

In [33]:
# change value in small_arr affect original array
small = arr[0:5]
small[:] = 99
arr

array([ 99,  99,  99,  99,  99, 100,   6,   7,   8,   9,  10])

In [34]:
# Therefore, you need to have a copy of orginal array
copy_arr = arr.copy()
copy_arr[:] = 0
copy_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [35]:
arr

array([ 99,  99,  99,  99,  99, 100,   6,   7,   8,   9,  10])

**2-D array**

In [36]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
# select row
arr_2d[0]

array([1, 2, 3])

In [38]:
# select column
arr_2d[:,0]

array([1, 4, 7])

In [39]:
# Getting individual element value
# Format is arr_2d[row][col] or arr_2d[row,col]
arr_2d[0][1]

2

In [40]:
arr_2d[0,1]

2

In [41]:
# 2D array slicing
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [42]:
arr_2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

**selecting array using boolen inside square bracket**

In [43]:
arr = np.random.randint(0,100,10)
arr

array([15, 75, 68, 24, 59, 42, 80,  0, 98, 28])

In [44]:
arr % 2 == 0

array([False, False,  True,  True, False,  True,  True,  True,  True,
        True])

In [45]:
# select number in array divied by 2
arr[arr % 2 == 0]

array([68, 24, 42, 80,  0, 98, 28])

In [46]:
# select number in array greater than 50
arr[arr > 50]

array([75, 68, 59, 80, 98])

<hr>

### Basic Numpy operator

In [47]:
arr = np.random.randint(0,10,5)
arr

array([5, 4, 1, 4, 7])

In [48]:
# sum
arr + arr

array([10,  8,  2,  8, 14])

In [49]:
# minus
arr - arr

array([0, 0, 0, 0, 0])

In [50]:
# multiply
arr * arr

array([25, 16,  1, 16, 49])

In [51]:
# power
arr ** 2

array([25, 16,  1, 16, 49], dtype=int32)

**Some familiar operation on array**

In [52]:
# square roots
np.sqrt(arr)

array([2.23606798, 2.        , 1.        , 2.        , 2.64575131])

In [53]:
# exponential (e^)
np.exp(arr)

array([ 148.4131591 ,   54.59815003,    2.71828183,   54.59815003,
       1096.63315843])

In [54]:
# max
np.max(arr)

7

In [55]:
# trigonometry
np.sin(arr)

array([-0.95892427, -0.7568025 ,  0.84147098, -0.7568025 ,  0.6569866 ])

In [56]:
np.log(arr)

array([1.60943791, 1.38629436, 0.        , 1.38629436, 1.94591015])